config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  root to: 'home#index'
  get '/home/about'
  get '/home/help'
  get '/home/contact'
  get '/home/index'
  get '/signup',  to: 'users#new'
  get '/login',to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users
  get '/check.txt', to: proc {[200, {}, ['it_works']]}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    before_save { email.downcase! }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence:
    true, length: { maximum: 255 },
    format:
    { with: VALID_EMAIL_REGEX },
     uniqueness: { case_sensitive: false }

     has_secure_password
     validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

     def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    include SessionsHelper
    def hello
        render html: "hello, world!"
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def help
  end

  def index 
  end

  def about
    
  end

  def contact
    
  end
  
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password]) 
      log_in user
      redirect_back_or user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end   
  end

  def destroy
    log_out
    redirect_to root_url
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user, only: [:edit, :update]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
    render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Profile Updated"
      redirect_to @user
    else
    render 'edit'
    end
  end
  

  private
    def user_params
     params.require(:user).permit(:name, :email, :password,:password_confirmation)
    end

    def logged_in_user
      unless logged_in?
        store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless  current_user?(@user)
    end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
    # Returns the full title on a per-page basis.
    def full_title(page_title = '')
    base_title = "Foli code App"
    if page_title.empty?
    base_title
    else
    page_title + " | " + base_title
    end
    end
        
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end

    def current_user
        if (user_id = session[:user_id])
          @current_user ||= User.find_by(id: user_id)
        elsif (user_id = cookies.encrypted[:user_id])
          user = User.find_by(id: user_id)
          if user && user.authenticated?(:remember, cookies[:remember_token])
            log_in user
            @current_user = user
          end
        end
      end

    def logged_in?
        !current_user.nil?
    end

    def log_out
        session.delete(:user_id)
        @current_user = nil
    end

    def current_user?(user)
        user && user == current_user
    end

    # Redirects to stored location (or to the default).
    def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
    end
    # Stores the URL trying to be accessed.
    def store_location
    session[:forwarding_url] = request.original_url if request.get?
    end
end

app/helpers/users_helper.rb
module UsersHelper
    
    def gravatar_for(user, size: 80)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
        end

end

app/views/home/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
The <a href="https://www.railstutorial.org/"><em>Ruby on Rails
Tutorial</em></a>, part of the
<a href="https://www.learnenough.com/">Learn Enough</a> family of
tutorials, is a
<a href="https://www.railstutorial.org/book">book</a> and
<a href="https://screencasts.railstutorial.org/">screencast series</a>
to teach web development with
<a href="https://rubyonrails.org/">Ruby on Rails</a>.
This is the sample app for the tutorial.
</p>

app/views/home/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
Contact the Ruby on Rails Tutorial about the sample app at the
<a href="https://www.railstutorial.org/contact">contact page</a>.
</p>

app/views/home/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
Get help on the Ruby on Rails Tutorial at the
<a href="https://www.railstutorial.org/help">Rails Tutorial Help page</a>.
To get help on this sample app, see the
<a href="https://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
book</a>.
</p>

app/views/home/index.html.erb
<h1>Sample App</h1>
<p>
This is the home page for the
<a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
sample application.
</p>
<%= link_to image_tag("cat.jpg", alt: "Rails logo", width: "200"),
"https://rubyonrails.org/" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div>
        <%= render './shared/navbar'%>
         <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>">
               <%= message %>
            </div>
          <% end %>
      </div>
     <%= yield %>
     <div class="container">
     
      <%= render './shared/footer'%>
      <%= debug(params) if Rails.env.development? %>
     </div>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            The form contains <%= pluralize(@user.errors.count, "error") %>.
        </div>
        <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li class=" text-danger pl-3">
                    <%= msg %>
                </li>
                <% end %>
        </ul>
    </div>
<% end %>

app/views/shared/_footer.html.erb
<section class="footer">
    <ul class="list-group">
        <li class="list-group-item">Home</li>
        <li class="list-group-item">About</li>
        <li class="list-group-item">Help</li>
        <li class="list-group-item">Contact</li>
        
    </ul>

</section>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to 'Cool App', root_path, class:'navbar-brand'%>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item ">
                    <%= link_to 'Home', home_index_path, class:'nav-link'%>
                </li>
                <li class="nav-item">
                    <%= link_to 'About', home_about_path, class:'nav-link'%>
                </li>
                <li class="nav-item">
                    <%= link_to 'Help', home_help_path, class:'nav-link'%>
                </li>
                <li class="nav-item">
                    <%= link_to 'Contact Us', home_contact_path, class:'nav-link'%>
                </li> 
                <% if logged_in?%>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <%=current_user.name%>
                </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <%= link_to 'Profile',current_user ,class:"dropdown-item"%>
                        <%= link_to 'Settings',edit_user_path(current_user) ,class:"dropdown-item"%>
                        <div class="dropdown-divider"></div>
                        <%= link_to 'Log Out',logout_path, method: :delete ,class:'dropdown-item'%>
                    </div>
                </li>
                <%else%>
                 <li class="nav-item">
                    <%= link_to 'Sign Up Now',signup_path, class:'nav-link'%>
                </li>
                <li class="nav-item">
                    <%= link_to 'Log In',login_path, class:'nav-link'%>
                </li>

                <%end%>
                
            </ul>

        </div>
</nav>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
    <%= render 'shared/error_messages' %>
        <div class="form-group">
            <%= f.label :name %>
                <%= f.text_field :name, class:"form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :email %>
                <%= f.email_field :email ,class:"form-control"%>
        </div>
        <div class="form-group">
            <%= f.label :password %>
                <%= f.password_field :password,class:"form-control" %>
        </div>
        <div class="form-group">
            <%= f.label :password_confirmation, "Password Confirmation" %>
                <%= f.password_field :password_confirmation, class:"form-control"%>
        </div>
        <div class="form-group">

            <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<% provide(:button_text, 'Save changes') %>
    <div class="container">
        <h1>Edit User</h1>
        <div class="row justify-content-center">
            <div class="col-md-6">
                <%= render 'form'%>
                    <div class="gravatar_edit">
                        <%= gravatar_for @user %>
                            <a href="https://gravatar.com/emails" target="_blank">change</a>
                    </div>
            </div>
        </div>
    </div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
    <div class="container">
        <h1>Sign up</h1>
        <div class="row justify-content-center">
            <div class="col-md-6">
              <%= render 'form'%>
            </div>
        </div>
    </div>
   

app/views/users/show.html.erb
<div class="container mt-5 mb-5">
    <% provide(:title, @user.name) %>
    <div class="row">
        <div class="col-md-4">
            <section class="">
                <h1>
                    <%= gravatar_for @user %>
                    <span class="small"> <%= @user.name %></span> 
                </h1>
            </section>
        </div>
    </div>
</div>